---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iot-web
  name: iot-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-web-app
  template:
    metadata:
      labels:
        app: iot-web-app
    spec:
      containers:
      - name: app
        image: iot_web:latest
        readinessProbe:
          httpGet:
            path: /api/health
            port: api-port
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: IOT_WEB_HOST
          value: "0.0.0.0"
        - name: IOT_WEB_WORKERS_COUNT
          value: "10"
        - name: IOT_WEB_DB_HOST
          value: "iot-web-db-service"
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
          name: api-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: iot-web
  name: iot-web-app-service
spec:
  selector:
    app: iot-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: api-port
    name: api-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-web-app
  namespace: iot-web
  labels:
    name: iot-web-app
spec:
  rules:
  - host: iot-web.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: iot-web-app-service
            port:
              name: api-port

---
