---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iot-web
  name: iot-web-db
spec:
  selector:
    matchLabels:
      app: iot-web-db
  template:
    metadata:
      labels:
        app: iot-web-db
    spec:
      containers:
      - name: database
        image: postgres:13.8-bullseye
        resources:
          limits:
            memory: "300Mi"
            cpu: "200m"
        env:
        - name: POSTGRES_PASSWORD
          value: "iot_web"
        - name: POSTGRES_USER
          value: "iot_web"
        - name: POSTGRES_DB
          value: "iot_web"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  namespace: iot-web
  name: "iot-web-db-service"
spec:
  selector:
    app: iot-web-db
  ports:
  - port: 5432
    targetPort: 5432
---
